name: Build and Publish to PyPI

on:
  push:
    tags:
      - "datacommons-mcp-v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify version matches tag
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/datacommons-mcp-v}"
          FILE_VERSION=$(grep '__version__' packages/datacommons-mcp/datacommons_mcp/version.py | sed 's/__version__ = "\(.*\)"/\1/')
          if [ "$TAG_VERSION" != "$FILE_VERSION" ]; then
            echo "Error: Tag version ($TAG_VERSION) doesn't match pyproject.toml version ($FILE_VERSION)."
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install uv
        run: |
          pip install uv

      - name: Build
        working-directory: packages/datacommons-mcp
        run: uv build

      - name: Publish
        working-directory: packages/datacommons-mcp
        run: uv publish --token ${{ secrets.PYPI_API_TOKEN }}
